[features]
seeds = false
skip-lint = false
[programs.devnet]
pindown = "FAU7uzegHAhsV8NYZ1BXzmCaAW8vVTKnNfknNgQcFB9u"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/dark/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
